### ISSUE TITLE
missing peer dependency

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/aws-es-client#3]
> http-aws-es@6.0.0 requires a peer of elasticsearch@^15.0.0 but none is installed. You must install peer dependencies yourself.

we probably have to `npm i -D elasticsearch` to make it go away

**Comment by alexlemaire** [comment]
Fixed. `http-aws-es` isn't maintained for around 2 years so switching from `elasticsearch@latest` to `elasticsearch@15.0.0` did the trick (`-D` didn't work with `latest`)

_Note:_ `elasticsearch` is the legacy client which is gonna be deprecated in the next months (see [here](https://github.com/elastic/elasticsearch-js-legacy)). I will create another client based on what we currently have but using the [new ElasticSearch client](https://www.elastic.co/blog/new-elasticsearch-javascript-client-released) (**in a new repo so it doesn't break what is in place and we have both clients usable**)

**Comment by Holger-Will** [comment]
no, please use the same repo and package so all our clients get the update...

**Comment by Holger-Will** [comment]
just keep our ougoing interface the same...

**Comment by alexlemaire** [comment]
ElasticSearch changed the way the response is handled. Now it sends a standardized object which contains the former `body` but also other information (see [here](https://github.com/kaskadi/aws-es-client/issues/4#issue-582425468))

That's why I wanted to create a new repo so I don't break what is in place and then carefully migrate everything to the new client

If I do it in this repo I can probably extend the class that handles response to only return `body`. But I'm not sure it's a good approach since I'm basically shutting down data which we may need (error messages, status, etc.)

**Comment by alexlemaire** [comment]
You can see how it looks like [here](https://github.com/kaskadi/aws-es-client-new) with the new client

**Comment by Holger-Will** [comment]
but that is exactly the purpose of versioning and version control, so that you do not cretae a new repo when things change...

**Comment by Holger-Will** [comment]
if you want to change the interface in a non backwards compatible way, raise the main version as per semVer!

**Comment by Holger-Will** [comment]
and again don't be too clever, if none of our users need the new data, there is no need to expose that just yet... don't make things more complex than they need to be.

**Comment by Holger-Will** [comment]
so as a fist step, i will accept a patch (PR) that changes the internal version used, but keeps the interface intact.

if you have any ideas of how to expose the new data in a backwards-compatible way, you can post the idea here

**Comment by alexlemaire** [comment]
I opened a [PR](https://github.com/kaskadi/aws-es-client/pull/6) with the new client implementation. The interface to create the client is identical as before. Only the data you retrieve is different because of how ElasticSearch client is returning its data now

For now I don't have a solid implementation idea that would make it backward-compatible so it's definitely a breaking change so I raised the version to `1.0.0` (was `0.0.1`)

If you want to make your apps compatible again you simply need to extract the `body` before you extract the field you want. Error handling can be impacted too but as for our applications I don't think we had a crazy error handling implementation so that shouldn't impact us much

_EDIT:_ PR merged!
